server.port=8081

# اسم الداتا بيز الجديدة (notification_db)
spring.datasource.url=jdbc:mysql://notification-db:3306/notification_db?updateReconnect=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=18102005#Mm
spring.jpa.hibernate.ddl-auto=update

# إعدادات الإيميل (نفس اللي كنت حاططها في البروجيكت الأساسي)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mohamedmostafa18102005@gmail.com
spring.mail.password=edljdjkqqtfwmori
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true