version: "3.8"



services:

  mysql-db:
    image: mysql:8.0
    container_name: bookstore-mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: 18102005#Mm
      MYSQL_DATABASE: bookstore

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p18102005#Mm"]
      interval: 10s
      timeout: 5s
      retries: 5

  bookstore:
    build: ./Book-Store-back
    container_name: bookstore-app
    restart: always

    ports:
      - "8080:8080"

    volumes:
      - ./uploads:/app/uploads

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bookstore?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 18102005#Mm
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      JWT_SECRET: your-very-secret-key-that-is-at-least-256-bits-long!
      JWT_EXPIRATION: 86400000


    depends_on:
      mysql-db:
        condition: service_healthy


  notification-db:
    image: mysql:8.0
    container_name: notification-mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: 18102005#Mm
      MYSQL_DATABASE: notification_db # اسم داتا بيز مختلف

    ports:
      - "3307:3306"

    volumes:
      - notification-mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p18102005#Mm"]
      interval: 10s
      timeout: 5s
      retries: 5

  notification-app:
    build: ./notification-service # بيقرا من فولدر الإشعارات
    container_name: notification-app
    restart: always

    ports:
      - "8081:8081" # بورت السيرفيس التانية

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://notification-db:3306/notification_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 18102005#Mm
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: mohamedmostafa18102005@gmail.com
      SPRING_MAIL_PASSWORD: edljdjkqqtfwmori

    depends_on:
      notification-db:
        condition: service_healthy

volumes:
  mysql-data:
  notification-mysql-data: # ضفنا الفضاء بتاع الداتا بيز التانية